import Topbar from "@/components/Topbar";
import SideNav from "@/components/SideNav"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <body>
        <Topbar />
        <div id="mypage">
        <SideNav />
        {children}
        </div>
        <div id="global-modal"></div>
      </body>
  );
}
